# app.py — Drew Is • AI Coach (Streamlit, 2025 refresh)
# - Left: Coach answer (provider-agnostic: OpenAI or Groq Llama-3.1-70B by default)
# - Optional live web context via Tavily for fresher answers
# - Right: Comparison cards (generated by the selected provider; availability checked per provider)
# - Temperature + max tokens controls
# - Brand styling (#FF9900 + dark)
# - Secrets/env-based keys; graceful fallbacks

import os, json, base64, textwrap, requests, time
from typing import List, Dict, Any, Optional
import streamlit as st

# ================= Page & Styles =================
st.set_page_config(page_title="AI Coach — Model Comparison", layout="wide")

st.markdown("""
<style>
  .stApp { background:#0d0d0d; color:#e6e6e6; font-family:'Segoe UI', system-ui, sans-serif; }
  h1,h2,h3,h4,h5 { color:#FF9900; }
  .section-title { margin: 0 0 .25rem 0; font-weight:700; color:#FF9900; }
  .subtle { color:#bdbdbd; font-size:0.9rem; }
  .box { background:#1a1a1a; border:1px solid #333; border-radius:10px; padding:1rem; }
  textarea, input[type="text"] { background:#1a1a1a !important; color:#f0f0f0 !important; }
  div.stButton > button { background:#FF9900; color:#000; font-weight:700; border:none; border-radius:8px; padding:.5rem 1rem; }
  div.stButton > button:hover { background:#e68a00; color:#fff; }
  .card { background:#141414; border:1px solid #2a2a2a; border-radius:10px; padding:1rem; margin-bottom:1rem; }
  .kpis { display:flex; flex-wrap:wrap; gap:.5rem; margin:.25rem 0 .5rem 0; }
  .pill { border:1px solid #333; border-radius:999px; padding:.25rem .6rem; font-size:.8rem; color:#cfcfcf; }
  .grid2 { display:grid; grid-template-columns:1fr 1fr; gap:1rem; }
  @media (max-width: 960px) { .grid2 { grid-template-columns:1fr; } }
  .footer-logo { display:flex; justify-content:center; margin:2rem 0 0; }
</style>
""", unsafe_allow_html=True)

st.title("AI Coach — Model Comparison")
st.caption("Compare strengths, tradeoffs, and ideal use-cases — with optional live web context.")

# ================= Secrets / Keys =================
OPENAI_API_KEY = st.secrets.get("OPENAI_API_KEY") or os.getenv("OPENAI_API_KEY", "")
GROQ_API_KEY   = st.secrets.get("GROQ_API_KEY")   or os.getenv("GROQ_API_KEY", "")
TAVILY_API_KEY = st.secrets.get("TAVILY_API_KEY") or os.getenv("TAVILY_API_KEY", "")

# ================== Sidebar Controls ==================
with st.sidebar:
    st.markdown("### Settings")
    provider = st.selectbox(
        "Provider",
        ["Groq (open-source default)", "OpenAI"],
        help="Groq runs open-source models like Llama-3.1-70B. OpenAI uses GPT-4.1/4o/etc if enabled on your key."
    )

    if provider.startswith("OpenAI"):
        if not OPENAI_API_KEY:
            st.warning("Missing OPENAI_API_KEY in secrets or env", icon="⚠️")
    else:
        if not GROQ_API_KEY:
            st.warning("Missing GROQ_API_KEY in secrets or env", icon="⚠️")

    use_web = st.toggle("Use live web context (Tavily)", value=True, help="Enrich answers & comparisons with fresh info.")
    if use_web and not TAVILY_API_KEY:
        st.info("Add TAVILY_API_KEY to enable web context.", icon="ℹ️")

    TEMPERATURE = st.slider("Temperature", 0.0, 1.5, 0.7, 0.1)
    ANSWER_MAXTOK = st.slider("Max tokens (Answer)", 256, 4096, 900, 64)
    COMPARE_MAXTOK = st.slider("Max tokens (Comparison)", 512, 8192, 1600, 64)

# ================= Provider/Model Catalog =================
# Default open-source text model via Groq:
DEFAULT_GROQ_TEXT = "llama-3.3-70b-versatile"  # fast + strong; adjust if you prefer 8b for cost
# Sensible OpenAI default:
DEFAULT_OPENAI_TEXT = "gpt-4.1"  # change to gpt-4o or your latest enabled model if you like

TEXT_MODEL = DEFAULT_GROQ_TEXT if provider.startswith("Groq") else DEFAULT_OPENAI_TEXT

CATALOG: Dict[str, List[Dict[str, str]]] = {
    "Text LLMs": [
        {"id": "gpt-4.1",           "label": "GPT-4.1",            "provider": "OpenAI"},
        {"id": "gpt-4o",            "label": "GPT-4o",             "provider": "OpenAI"},
        {"id": "llama-3.1-70b",     "label": "Llama-3.1-70B",      "provider": "Meta (via Groq)"},
        {"id": "llama-3.1-8b",      "label": "Llama-3.1-8B",       "provider": "Meta (via Groq)"},
        {"id": "mixtral-8x7b",      "label": "Mixtral-8x7B",       "provider": "Mistral (via Groq)"},
        {"id": "claude-3.5",        "label": "Claude 3.5",         "provider": "Anthropic (external)"},
        {"id": "gemini-1.5",        "label": "Gemini 1.5",         "provider": "Google (external)"},
        {"id": "cohere-command-r",  "label": "Cohere Command R",   "provider": "Cohere (external)"},
    ],
    "Image Models": [
        {"id":"sdxl",         "label":"Stable Diffusion XL",   "provider":"Stability (open)"},
        {"id":"flux",         "label":"FLUX.1",                "provider":"Black Forest (open)"},
        {"id":"openai-image", "label":"OpenAI Image (latest)", "provider":"OpenAI"},
        {"id":"midjourney",   "label":"Midjourney",            "provider":"Midjourney"},
    ],
    "Video Models": [
        {"id":"runway-gen3",  "label":"Runway Gen-3",          "provider":"Runway"},
        {"id":"luma-dream",   "label":"Luma Dream Machine",    "provider":"Luma"},
        {"id":"pika",         "label":"Pika",                  "provider":"Pika"},
    ],
    "Avatar Models": [
        {"id":"heygen",     "label":"HeyGen Avatars", "provider":"HeyGen"},
        {"id":"synthesia",  "label":"Synthesia",      "provider":"Synthesia"},
        {"id":"d-id",       "label":"D-ID",           "provider":"D-ID"},
    ],
}

# ================= Utilities =================
def _headers_openai():
    return {"Authorization": f"Bearer {OPENAI_API_KEY}", "Content-Type": "application/json"}

def _headers_groq():
    return {"Authorization": f"Bearer {GROQ_API_KEY}", "Content-Type": "application/json"}

@st.cache_data(ttl=600)
def list_openai_models() -> set:
    if not OPENAI_API_KEY:
        return set()
    try:
        r = requests.get("https://api.openai.com/v1/models", headers=_headers_openai(), timeout=30)
        r.raise_for_status()
        return {m["id"] for m in r.json().get("data", [])}
    except Exception as e:
        print("OpenAI model list fetch failed:", e)
        return set()

@st.cache_data(ttl=600)
def list_groq_models() -> set:
    if not GROQ_API_KEY:
        return set()
    try:
        r = requests.get("https://api.groq.com/openai/v1/models", headers=_headers_groq(), timeout=30)
        r.raise_for_status()
        return {m["id"] for m in r.json().get("data", [])}
    except Exception as e:
        print("Groq model list fetch failed:", e)
        return set()

AVAILABLE_OPENAI = list_openai_models()
AVAILABLE_GROQ   = list_groq_models()

def availability_for(label: str, model_id: str, prov_label: str) -> str:
    """Rough availability map based on provider model lists."""
    if "OpenAI" in prov_label:
        # allow common aliases
        ids = AVAILABLE_OPENAI
        return "active" if any(x in ids for x in [model_id, model_id.replace("gpt-4.1","gpt-4o")]) else "not-enabled"
    if "Groq" in prov_label:
        ids = AVAILABLE_GROQ
        # groq uses ids like 'llama-3.1-70b-versatile'
        key = "llama-3.1-70b" if model_id == "llama-3.1-70b" else model_id
        return "active" if any(key in x for x in ids) else "not-enabled"
    # External providers we don't query here
    return "not-enabled"

# ================= Web Search (Tavily) =================
@st.cache_data(ttl=600)
def tavily_search_and_summarize(query: str) -> Dict[str, Any]:
    if not TAVILY_API_KEY:
        return {"summary": "", "sources": []}
    try:
        # 1) Search
        resp = requests.post(
            "https://api.tavily.com/search",
            json={"api_key": TAVILY_API_KEY, "query": query, "search_depth": "advanced", "max_results": 5},
            timeout=30
        )
        resp.raise_for_status()
        data = resp.json()
        results = data.get("results", [])
        # 2) Concatenate snippets for context
        passages = "\n\n".join([f"- {r.get('title','')}: {r.get('content','')}" for r in results])
        # 3) Return minimal structure; the LLM will read 'web_context'
        sources = [{"title": r.get("title",""), "url": r.get("url","")} for r in results]
        return {"summary": data.get("answer",""), "passages": passages, "sources": sources}
    except Exception as e:
        print("Tavily error:", e)
        return {"summary": "", "sources": []}

# ================= LLM Calls =================
def call_openai(messages: List[Dict[str,str]], max_tokens: int, temperature: float, response_format: Optional[dict]=None) -> str:
    payload = {
        "model": TEXT_MODEL,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": temperature
    }
    if response_format:
        payload["response_format"] = response_format
    r = requests.post("https://api.openai.com/v1/chat/completions", headers=_headers_openai(), json=payload, timeout=60)
    if r.status_code != 200:
        raise RuntimeError(f"OpenAI error: {r.status_code} {r.text[:800]}")
    return r.json()["choices"][0]["message"]["content"]

def call_groq(messages: List[Dict[str,str]], max_tokens: int, temperature: float, response_format: Optional[dict]=None) -> str:
    payload = {
        "model": TEXT_MODEL,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": temperature
    }
    # Groq is "OpenAI compatible" under /openai/v1
    r = requests.post("https://api.groq.com/openai/v1/chat/completions", headers=_headers_groq(), json=payload, timeout=60)
    if r.status_code != 200:
        raise RuntimeError(f"Groq error: {r.status_code} {r.text[:800]}")
    return r.json()["choices"][0]["message"]["content"]

def llm_chat(messages, max_tokens, temperature, response_format=None) -> str:
    if provider.startswith("OpenAI"):
        return call_openai(messages, max_tokens, temperature, response_format)
    else:
        return call_groq(messages, max_tokens, temperature, response_format)

# ================= Coach Answer =================
def coach_answer(user_prompt: str, web_on: bool) -> str:
    web_part = ""
    if web_on and user_prompt.strip():
        web = tavily_search_and_summarize(user_prompt.strip())
        if web.get("passages"):
            web_part = f"\n\n[Web context]\n{web['passages']}\n\n"

    sys = (
        "You are 'AI Tools Coach' for professionals. Be concise, candid, tactical, and forward-looking. "
        "Use short sections and bullets when helpful. State tradeoffs bluntly. If you used web context, cite the sources inline as (Source 1), (Source 2), etc, and add a short 'Sources' list at the end with titles and URLs."
    )

    user = f"{user_prompt.strip()}\n{web_part}".strip()

    return llm_chat(
        [{"role":"system","content":sys},{"role":"user","content":user}],
        max_tokens=ANSWER_MAXTOK,
        temperature=TEMPERATURE
    )

# ================= Comparison Builder =================
def build_comparison(category: str, task_prompt: str, web_on: bool) -> dict:
    models = CATALOG.get(category, [])
    names = [m["label"] for m in models]
    availability_map = {
        m["label"]: availability_for(m["label"], m["id"], m["provider"])
        for m in models
    }

    type_map = {
        "Text LLMs": "text", "Image Models": "image", "Video Models": "video", "Avatar Models": "avatar"
    }

    schema = textwrap.dedent("""
    Return strict JSON ONLY (no code fences, no commentary):
    {
      "items": [
        {
          "name": "Exact model label from the list",
          "provider": "OpenAI|Meta (via Groq)|Mistral (via Groq)|Stability (open)|Black Forest (open)|Midjourney|Runway|Luma|Pika|Anthropic (external)|Google (external)|Cohere (external)",
          "type": "text|image|video|avatar",
          "availability": "active|not-enabled",
          "strengths": ["...", "..."],
          "limits": ["...", "..."],
          "ideal": ["...", "..."],
          "notes": "one or two-line note",
          "tiers": {
            "reasoning": "1|2|3|n/a",  // 3 = strongest capability overall
            "latency": "1|2|3|n/a",    // 1 = fastest typical latency
            "price": "1|2|3|n/a",      // 1 = cheapest typical cost
            "context": "small|medium|large|huge|n/a"
          }
        }
      ],
      "summary": "One-paragraph summary: who should pick what for this task.",
      "sources": [{"title":"...", "url":"..."}]
    }
    """).strip()

    web_context = ""
    if web_on and task_prompt.strip():
        web = tavily_search_and_summarize(task_prompt.strip())
        if web.get("passages"):
            web_context = f"\n\n[Web context]\n{web['passages']}\n\nInclude relevant citations in 'sources'."

    sys = (
        "You are an impartial analyst of current AI model capabilities. Be specific and avoid speculation. "
        "Respect the provided availability map: if 'not-enabled', describe capabilities generally but do not imply it's usable on this account."
    )
    user = textwrap.dedent(f"""
    Category: {category}
    Task prompt: {task_prompt}

    Models to include (exact labels, in this order):
    {", ".join(names)}

    Availability map (from this account):
    {json.dumps(availability_map, ensure_ascii=False)}

    Type mapping by category:
      - "Text LLMs" -> "text"
      - "Image Models" -> "image"
      - "Video Models" -> "video"
      - "Avatar Models" -> "avatar"

    {schema}
    {web_context}
    """).strip()

    content = llm_chat(
        [{"role":"system","content":sys},{"role":"user","content":user}],
        max_tokens=COMPARE_MAXTOK,
        temperature=TEMPERATURE,
    )
    # Try to parse JSON; if the model returns extra text, extract JSON block heuristically
    def _coerce_json(s: str) -> dict:
        s = s.strip()
        # Find first { ... } block
        try:
            if not s.startswith("{"):
                first = s.find("{")
                last = s.rfind("}")
                if first != -1 and last != -1 and last > first:
                    s = s[first:last+1]
            return json.loads(s)
        except Exception:
            return {"items": [], "summary": "", "sources": []}

    data = _coerce_json(content)

    # Guard: ensure each requested name appears, even if empty
    found = {it.get("name") for it in data.get("items", [])}
    for m in models:
        nm = m["label"]
        if nm not in found:
            _type = type_map.get(category, "text")
            (data.setdefault("items", [])).append({
                "name": nm, "provider": m["provider"], "type": _type,
                "availability": availability_map.get(nm,"not-enabled"),
                "strengths": [], "limits": [], "ideal": [],
                "notes": "", "tiers": {"reasoning":"n/a","latency":"n/a","price":"n/a","context":"n/a"}
            })
    return data

# ================= Footer Logo =================
def render_footer_logo(path="Drew Is small logo 50.jpg", width=120):
    try:
        with open(path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        st.markdown(
            f"""
            <div class='footer-logo'>
              <img src="data:image/jpeg;base64,{b64}" width="{width}" />
            </div>
            """,
            unsafe_allow_html=True,
        )
    except Exception as e:
        st.caption("")  # quiet fallback

# ================= UI =================
left, right = st.columns([1,1], gap="large")

with left:
    st.markdown("<div class='section-title'>Ask AI Coach</div>", unsafe_allow_html=True)
    st.markdown("<div class='subtle'>Get a straight answer for your situation.</div>", unsafe_allow_html=True)
    user_prompt = st.text_area(" ", placeholder="Type your question…", height=140, label_visibility="collapsed")
    if st.button("Get Coach Answer"):
        if not user_prompt.strip():
            st.warning("Please enter a prompt.")
        else:
            try:
                st.markdown("<div class='box'>", unsafe_allow_html=True)
                st.markdown("#### Coach Answer")
                st.write(coach_answer(user_prompt, use_web))
                st.markdown("</div>", unsafe_allow_html=True)
            except Exception as e:
                st.error(str(e))

with right:
    st.markdown("<div class='section-title'>Compare Models</div>", unsafe_allow_html=True)
    st.markdown("<div class='subtle'>See strengths, limits, and ideal use-cases.</div>", unsafe_allow_html=True)
    category = st.selectbox("Category", list(CATALOG.keys()))
    cmp_prompt = st.text_area("Task for comparison", placeholder="e.g., Summarize a 50-page contract and extract risk clauses", height=140)
    if st.button("Run Comparison"):
        if not cmp_prompt.strip():
            st.warning("Please enter a task prompt.")
        else:
            try:
                data = build_comparison(category, cmp_prompt, use_web)
                items = data.get("items", [])

                st.markdown("<div class='grid2'>", unsafe_allow_html=True)
                for item in items:
                    tiers = item.get("tiers", {}) or {}
                    strengths = item.get("strengths") or []
                    limits = item.get("limits") or []
                    ideal = item.get("ideal") or []
                    st.markdown("<div class='card'>", unsafe_allow_html=True)
                    st.markdown(f"**{item.get('name','(unknown)')}**  \n*{item.get('provider','')}, {item.get('type','')}*")
                    st.caption(f"Availability: {item.get('availability','unknown')}")
                    if item.get("notes"):
                        st.write(item["notes"])
                    st.markdown("<div class='kpis'>", unsafe_allow_html=True)
                    st.markdown(f"<span class='pill'>reasoning {tiers.get('reasoning','n/a')}</span>", unsafe_allow_html=True)
                    st.markdown(f"<span class='pill'>latency {tiers.get('latency','n/a')}</span>", unsafe_allow_html=True)
                    st.markdown(f"<span class='pill'>price {tiers.get('price','n/a')}</span>", unsafe_allow_html=True)
                    st.markdown(f"<span class='pill'>context {tiers.get('context','n/a')}</span>", unsafe_allow_html=True)
                    st.markdown("</div>", unsafe_allow_html=True)

                    if strengths:
                        st.markdown("**Strengths**")
                        st.write("• " + "\n• ".join(strengths))
                    if limits:
                        st.markdown("**Limits**")
                        st.write("• " + "\n• ".join(limits))
                    if ideal:
                        st.markdown("**Ideal for**")
                        st.write("• " + "\n• ".join(ideal))
                    st.markdown("</div>", unsafe_allow_html=True)
                st.markdown("</div>", unsafe_allow_html=True)

                if data.get("summary"):
                    st.markdown("### Summary")
                    st.write(data["summary"])

                # optional: list sources if web context was used
                srcs = data.get("sources") or []
                if srcs:
                    st.markdown("**Sources**")
                    for i, s in enumerate(srcs, 1):
                        title = s.get("title","Source")
                        url = s.get("url","")
                        st.write(f"{i}. [{title}]({url})")

            except Exception as e:
                st.error(str(e))

render_footer_logo()

